name: passenger_app
description: Passenger app for RikshaRide
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.0.5
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true